#:schema ../../schemas/json/ttheme-palette.json
[meta]
name = "dusk"
signature = ["cursor", "foreground", "background"]

[colors]
background = "#101010"
foreground = "#f0f0f0"
cursor = "#ff8800"
selection_background = "#303030"
ansi = [
  "#000000",
  "#111111",
  "#222222",
  "#333333",
  "#444444",
  "#555555",
  "#666666",
  "#777777",
  "#888888",
  "#999999",
  "#aaaaaa",
  "#bbbbbb",
  "#cccccc",
  "#dddddd",
  "#eeeeee",
]
