# yaml-language-server: $schema=../../schemas/json/bxci.schema-3.x.json
project:
  name: some-project
  type: npm

stages:
  my stage:
    steps:
      - echo first

output:
  package:
    - channel: stable
