# yaml-language-server: $schema=../../schemas/json/opensrm.json
# This file is INVALID - target must be between 0 and 1
apiVersion: srm/v1
kind: ServiceReliabilityManifest
metadata:
  name: invalid-service
  team: platform
  tier: standard
spec:
  type: api
  slos:
    availability:
      target: 99.9
  ownership:
    team: platform
