version: 2
updates:
  - package-ecosystem: 'github-actions'
    cooldown:
      default-days: 14
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        patterns:
          - '*'
