# Changes to continuous integration.
CI:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'

# Changes to JavaScript.
'cli.js':
  - changed-files:
      - any-glob-to-any-file:
          - 'cli.js'
          - 'package.json'

# Changes to configuration.
config:
  - changed-files:
      - any-glob-to-any-file:
          - '.editorconfig'
          - 'eslint.config.js'
          - '.gitignore'
          - '.gitattributes'

# Changes to documentation.
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

# Changes to website files. Generally, they must NOT be updated.
WARNING_WebsiteFiles:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/bin/**/*'
          - 'src/css/**/*'
          - 'src/img/**/*'
          - 'src/js/**/*'
          - '**/*.sln'
          - '**/*.cshtml'
          - '**/*.config'
          - '**/*.webinfo'
          - '**/*.ico'
          - '**/*.txt'
# Do not add "src/{api,schemas,test}", etc. directories;
# they are not special.
