# yaml-language-server: $schema=../../schemas/json/bxci.schema-2.x.json
project:
  type: npm

stages:
  first:
    steps:
      - echo "Hello"

output:
  docker:
    dockerfile: path/to/Dockerfile
    image_name: my-image
    this_is_not_allowed: true
