# yaml-language-server: $schema=../../schemas/json/bxci.schema-2.x.json
project:
  name: some-project
  type: npm

stages:
  my stage:
    steps:
      - echo first

output:
  package:
    publish:
      - channel: stable
