project:
  name: any

stages:
  first:
    steps:
      - echo "Hello"

output:
  docker:
    dockerfile: Dockerfile
    image_name: britebill/image-name
    args:
      - key: GIT_COMMIT

      - key: VERSION
        value: some value
