# yaml-language-server: $schema=../../schemas/json/vhwdebugger-binding-schema.json
version: '1.0'

debuggers:
  debugger1:
    type: lauterbach
    port: 5315
    lauterbach:
      pack-len: 512
    isystem:
      disable-winidea-polling: true
