#:schema ../../schemas/json/git-cliff.json

[changelog]
trim = "yes"
postprocessors = [{ replace = "missing pattern" }]

[git]
processing_order = ["unknown_step"]
sort_commits = "ascending"
limit_commits = 0
commit_parsers = [{ message = "^feat", skip = "false" }]
link_parsers = [{ pattern = "#(\\d+)" }]

[remote]
offline = "false"

[bump]
bump_type = "micro"
