project:
  name: some-project
  type: npm

config:
  jenkins_runtime:
    docker:
      image: remote-host.com/image-name:tag
      dockerfile: .ci/Dockerfile

  branch:
    disable_validation: false
    branch_pattern: "^master$|^release/.+$"

  build:
    clean_workspace_after_run: false

services:
  - Elasticsearch
  - Mysql
  - Mssql

environment:
  my_env_var: value
  ANOTHER_VAR: value
  invalid-name: value
  __CFBundleIdentifier: some value

jenkinsEnvironment:
  - SOME_VALID_VALUE
  - some value (invalid)

archive:
  - some-file.txt
  - target/*.jar

stages:
  my stage:
    steps:
      - echo first
  another:
    steps:
      - npm run lint
  Another step:
    when:
      branch: "^master$"
    steps:
      - echo last

output:
  docker:
    dockerfile: path/to/Dockerfile
    image_name: my-image
    publish:
      branch: "^master$"
      credentials: SECRET

  helm:
    path: k8s/project-name
    updates:
      - file: Chart.yaml
        properties:
          - key: chartVersion
      - file: Another.yaml
        properties:
          - key: something
    publish:
      branch: "^master$|^release/.+$"
      credentials: SECRET
