# Test to check buildConfig validation
platform:
  vendor: Imagination Technologies
  name: alpineB
  description: Alpine model v2
  buildConfig: ALPINE_lower
  version: '1'
  license: Copyright (c) Imagination Technologies. All rights reserved.
  documentationFile:
    builtin: false
    path: index.html
  coreDescriptionFile:
    builtin: false
    path: alpineB.YAML
  launchConfig: Alpine Model
