# yaml-language-server: $schema=../../schemas/json/value-add-transformer.json
apiVersion: builtin
kind: ValueAddTransformer
metadata:
  name: notImportantHere
value: my-server
targets:
  - selector:
      kind: Deployment
