# yaml-language-server: $schema=../../schemas/json/github-pages-jekyll.json
safe: false
lsi: true
incremental: true
highlighter: coderay
gist:
  noscript: true
kramdown:
  math_engine: katex
  syntax_highlighter: coderay
