name: "🐛 Bug report"
description: Report errors or unexpected behavior
labels:
  - Issue-Bug
body:
  - type: markdown
    attributes:
      value: |
        Please make sure to [search for existing issues](https://github.com/SchemaStore/schemastore/issues) before filing a new one!
  - type: dropdown
    attributes:
      label: Area with issue?
      multiple: false
      options:
        - JSON Schema
        - Documentation
        - Build server
        - Web server
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: true
  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: textarea
    attributes:
      label: YAML or JSON file that does not work.
      placeholder: |
        This file is used to reproduce the problem.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: IDE or code editor.
      description: Some issues are related to IDE or code editor.
      multiple: false
      options:
        - Visual Studio Code
        - Visual Studio
        - IntelliJ and it's derivatives
        - Other
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Are you making a PR for this?
      description: Who will make the PR?
      multiple: false
      options:
        - Yes, I will create a PR.
        - No, someone else must create the PR.
    validations:
      required: true
