name: "⭐ Request (feature)"
description: Propose something new for the SchemaStore web site or build server.
labels:
  - Feature-for-website-or-build-server
body:
  - type: textarea
    attributes:
      label: Description of the feature / enhancement.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please limit one request per issue.
