name: '⭐ Request (feature)'
description: Propose something new for the SchemaStore web site or build server.
labels:
  - Feature-for-website-or-build-server
body:
  - type: textarea
    attributes:
      label: Description of the feature / enhancement.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please limit one request per issue.
  - type: dropdown
    attributes:
      label: Are you making a PR for this?
      description: Who will make the PR?
      multiple: false
      options:
        - Yes, I will create a PR.
        - No, someone else must create the PR.
    validations:
      required: true
