name: "⭐ Request (schema)"
description: Request to add a new JSON schema.
labels:
  - Request-for-new-schema
body:
  - type: textarea
    attributes:
      label: Description of the JSON schema.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Supporting information.
      placeholder: |
        URL where you can find the schema documentation.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please limit one request per issue.
