#:schema ../../schemas/json/gitleaks.json

[extend]
path = "common_config.toml"
useDefault = true

[[rules]]
description = "missing id"
regex = '''secret'''
secretGroup = -1
entropy = -0.1
skipReport = "yes"

[[rules.allowlists]]
regexTarget = "column"

[rules.allowlist]
paths = ['''deprecated-only''']

[[allowlists]]
condition = "XOR"

[[allowlists]]
targetRules = ["missing-criteria"]

[allowlist]
paths = ['''deprecated-only''']
