#:schema ../../schemas/json/gitleaks.json

[extend]
path = "common_config.toml"
useDefault = true

[[rules]]
description = "missing id"
regex = '''secret'''
secretGroup = -1
entropy = -0.1
skipReport = "yes"

[[rules.allowlists]]
regexTarget = "column"

[[allowlists]]
condition = "XOR"
