# yaml-language-server: $schema=../../schemas/json/sourcery_yaml_schema.json
ignore: []

refactor:
  include: []
  skip:
    - use-fstring-for-formatting
  rule_types:
    - refactoring
    - suggestion
    - comment
  python_version: '3.9'

metrics:
  quality_threshold: 25.0

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false

github:
  labels: []
  ignore_labels: [sourcery-ignore]
  request_review: author
  sourcery_branch: sourcery/{base_branch}
