# yaml-language-server: $schema=../../schemas/json/github-workflow.json
name: all-steps-must-contain-run-or-uses
on:
  - push
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: foo
      - name: foo
        run: foo
