# yaml-language-server: $schema=../../schemas/json/github-workflow.json
on:
  pull_request:
    # this is a typo! it should be `paths-ignore`
    ignore-paths: ['foo.yaml']

jobs:
  with:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
