# yaml-language-server: $schema=../../schemas/json/github-workflow.json
name: Invalid cache mode
on: push
cache-mode: invalid
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test
