# yaml-language-server: $schema=../../schemas/json/github-workflow.json
name: Invalid container entrypoint
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18
      entrypoint: node
    steps:
      - run: node --version
