# yaml-language-server: $schema=../../schemas/json/github-workflow.json
name: Invalid container command
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18
      command: npm test
    steps:
      - run: npm test
