# yaml-language-server: $schema=../../schemas/json/github-workflow.json
name: invalid issue comment type
on:
  issue_comment:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test
