# yaml-language-server: $schema=../../schemas/json/github-workflow.json
on: push
jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      id-token: read
    steps:
      - run: echo example
