# yaml-language-server: $schema=../../schemas/json/github-workflow.json
name: publish on release
on:
  release:
    types:
      - published
jobs:
  build-and-publish:
    uses: ./.github/workflows/somefile.exe
    secrets:
      api_token: ${{ secrets.API_TOKEN }}
