name: Test runs-on
on:
  push:
    branches:
      - master
jobs:
  self-hosted-custom:
    runs-on:
      - self-hosted
      - x86
      - windows
      - gpu
      - large
      - 5
    steps:
      - run: echo 'Hello from self-hosted ${{ runner.os }}'
