# yaml-language-server: $schema=../../schemas/json/github-workflow.json
name: Test runs-on
on:
  push:
    branches:
      - master
jobs:
  self-hosted-custom:
    runs-on:
    steps:
      - run: echo 'Hello from self-hosted ${{ runner.os }}'
