name: Invalid with type
on:
  - push
jobs:
  with:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with: '{"node-version":"12"}'
      - run: npm run lint
      - run: npm test
