name: inputs
on:
  workflow_dispatch:
    inputs:
      choice:
        required: false
        type: choice
        description: choice
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
