name: inputs
on:
  workflow_dispatch:
    inputs:
      bool:
        required: false
        type: boolean
        description: bool
        default: "true"
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
