# yaml-language-server: $schema=../../schemas/json/hws-config.json
# Hardware Sentry

# Number of jobs that Hardware Sentry can run simultaneously.
jobPoolSize: 30

# Discovery cycle.
discoveryCycle: 20

# Internal collect interval.
collectPeriod: 1m

# Debug mode of the core engine.
loggerLevel: debug

# Display the configured hostname in the Host Resource `host.name` attribute instead of the resolved FQDN.
resolveHostnameToFqdn: true

# Forces all the network calls to be executed in sequential order.
sequential: false

# Disable hardware alerts.
disableAlerts: false

extraLabels:
  site: Datacenter 1 # Customize this value with your own site naming convention. (Dedicating 1 collector to 1 site is a good practice.)

extraMetrics:
  hw.site.carbon_density_grams: 230 # in g/kWh
  # Carbon dioxide produced per kilowatt-hour.
  # The average is 230g/kWh for Europe.
  # The average is 309g/kWh for Texas, USA.
  # The average is 40g/kWh for Ontario, Canada.
  # The average is 712g/kWh for Queensland, Australia.
  # Source: https://app.electricitymap.org/map

  hw.site.electricity_cost_dollars: 0.12 # in $/kWh
  # Electricity cost per kilowatt-hour.
  # The average is $0.12/kWh for non-household in Europe.
  # The average is $0.159/kWh for non-household in the USA.
  # The average is $0.117/kWh for non-household in Canada.
  # The average is $0.225/kWh for non-household in Australia.
  # Source: https://www.globalpetrolprices.com/electricity_prices/

  hw.site.pue_ratio: 1.8
  # Power Usage Effectiveness. A ratio describing how efficiently a computer data center uses energy. The ideal ratio is 1.

exporter:
  otlp:

# Missing hosts!
hosts:
