#:schema ../../schemas/json/typst.json
# Fails because package.authors is not an array
[package]
name = "wrong-authors"
version = "0.1.0"
entrypoint = "lib.typ"
authors = "Just Me"                       # INVALID TYPE (should be array)
license = "MIT"
description = "Authors should be a list."
