#:schema ../../schemas/json/typst.json
# Fails because package.version is not a valid SemVer string
[package]
name = "bad-version"
version = "1.2"                                             # INVALID PATTERN (missing patch)
entrypoint = "lib.typ"
authors = ["Version Violator"]
license = "MIT"
description = "This package has an invalid version format."
