#:schema ../../schemas/json/typst.json
# Fails because package.name contains uppercase characters
[package]
name = "Invalid-Name"                             # INVALID PATTERN
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Rule Breaker"]
license = "MIT"
description = "This package has an invalid name."
