#:schema ../../schemas/json/typst.json
# Fails because package.version is missing
[package]
name = "missing-version"
# version = "0.1.0" # MISSING
entrypoint = "lib.typ"
authors = ["Incomplete Author"]
license = "MIT"
description = "This package is missing a version."
