# yaml-language-server: $schema=../../schemas/json/jfrog-pipelines.json
pipelines:
  - name: test_pipeline_1
    steps:
      - name: publish_go_module_test
        type: GoPublishModule
        configuration:
          sourceLocation: .
          version: v0.0.0
          autoPublishBuildInfo: true
