# yaml-language-server: $schema=../../schemas/json/jfrog-pipelines.json
pipelines:
  - name: test_pipeline_1
    steps:
      - name: docker_releaseBundle
        type: CreateReleaseBundle
        configuration:
          inputResources:
            - name: ns_promotedInfo
          dryRun: false
        execution:
          onSuccess:
            - echo "Job well done!"
