pipelines:
  - name: test_pipeline_1
    steps:
      - name: helm_pub
        type: HelmPublish
        configuration:
          autoPublishBuildInfo: true
          lint: true
          helmVersion: 3
        execution:
          onStart:
            - echo "Preparing for work..."
