pipelines:
  - name: test_pipeline_1
    steps:
      - name: HelmDeploy
        type: HelmDeploy
        configuration:
          helmVersion: 3
        execution:
          onStart:
            - echo "Preparing for work..."
