pipelines:
  - name: test_pipeline_1
    steps:
      - name: download_linux
        type: Bash
        configuration:
          integrations:
            - name: artifactory_integration
          inputResources:
            - name: connecting_resource
