pipelines:
  - name: test_pipeline_1
    steps:
      - name: gradle_build_step
        type: GradleBuild
        configuration:
          configFileName: gradle-art-config
        execution:
          onStart:
            - gradle --version
