# yaml-language-server: $schema=../../schemas/json/bxci.schema-2.0.0.json
project:
  name: some-project
  type: npm

stages:
  my stage:
    steps:
      - echo first

output:
  docker:
    dockerfile: path/to/Dockerfile
    image_name: my-image
    publish:
      branch: '^master$'
      credentials: SECRET

  helm:
    path: k8s/project-name
    updates:
      - file: Chart.yaml
        properties:
          - key: chartVersion
      - file: Another.yaml
        properties:
          - key: something
    publish:
      branch: '^master$|^release/.+$'
      credentials: SECRET
