# yaml-language-server: $schema=../../schemas/json/prometheus.json
scrape_configs:
  - job_name: prometheus
    scrape_native_histograms: 'true'
    static_configs:
      - targets:
          - nativehisto:8080
