#:schema ../../schemas/json/cargo.json
[package]
name = "conflicting-registry-sources"
version = "0.1.0"

[dependencies]
serde = { version = "1", registry = "my-registry", registry-index = "https://example.com/index" }
