#:schema ../../schemas/json/cargo.json
[package]
name = "conflicting-dependency-sources"
version = "0.1.0"

[dependencies]
regex = { git = "https://github.com/rust-lang/regex.git", path = "../regex" }
