#:schema ../../schemas/json/lychee.json

verbose = "loud"
format = "md"
mode = "sparkles"
threads = 0
max_concurrency = 0
include_fragments = true
method = []
accept = [{ code = 200 }]

[hosts."example.com"]
unknown = true
