#:schema ../../schemas/json/pyproject.json
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pep808-negative-example"
description = "An example package that incorrectly lists a string field in dynamic"
requires-python = ">=3.9"
dynamic = ["version", "requires-python"]
