#:schema ../../schemas/json/pyproject.json
[tool.poetry]
name = "foo"
version = "1.2.3"
description = "bar"
authors = ["Poetry"]
source = [
  { name = "pytorch-cpu", url = "https://download.pytorch.org/whl/cpu", priority = 1 },
]
