#:schema ../../schemas/json/pyproject.json
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "extension-project"
version = "0.1.0"

[tool.setuptools]
ext-modules = [{ name = "extension_project.foo" }]
