# name: 'Maintenance: Check Broken URLs'
# # on:
# #   schedule:
# #     - cron: '2 22 * * *' # Runs at 10:02 every day
# #   push:
# #   pull_request:
# on: ['push', 'pull_request']
# permissions: 'write-all'
# jobs:
#   brokenurl:
#     if: github.repository == 'SchemaStore/schemastore'
#     runs-on: 'ubuntu-latest'
#     permissions: 'write-all'
#       # issues: 'write'
#     steps:
#       - uses: 'actions/checkout@v4'
#       - uses: 'actions/setup-node@v4'
#         with:
#           node-version: '18'
#           cache: 'npm'
#           cache-dependency-path: './package-lock.json'
#       - run: 'npm clean-install'
#       - run: |
#           gh issue create --title "I found a bug" --body "Nothing works"
#           echo "this is body 2" | gh issue edit 4128 --body-file -
#         env:
#           GH_TOKEN: '${{ github.token }}'
#       # - run: 'node ./cli.js maintenance'
