name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  triage:
    if: github.repository == 'SchemaStore/schemastore'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
