name: 'Maintenance: Label Pull Requests'
on:
  - pull_request_target

jobs:
  triage:
    if: github.repository == 'SchemaStore/schemastore'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
