name: 'Maintenance: Label Pull Requests'
on:
  - pull_request_target

jobs:
  triage:
    if: github.repository == 'SchemaStore/schemastore'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
