name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '18'
          cache-dependency-path: src/package-lock.json
      - name: npm ci
        run: |
          cd src
          npm ci
      - name: npm run build
        run: |
          cd src
          npm run build
