name: Prettier

on: [pull_request_target]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          prettier_version: 2.1.2
          prettier_options: --config ./src/.prettierrc.json --write .
          only_changed: true
          same_commit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
