name: "Close stale PRs"
on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'SchemaStore'
    steps:
      - uses: actions/stale@v5
        with:
          stale-pr-message: "This PR is stale because it has been open 60 days with no activity. Comment or this will be closed in 7 days."
          close-pr-message: "This PR was closed because it has been stalled for 7 days with no activity."
          days-before-issue-stale: -1
          days-before-issue-close: -1
